[project]
    name            = "LangDojo"
    version         = "0.1.0"
    description     = "LangDojo is a tool for exploring the capabilities of LLMs."
    readme          = "README.md"
    requires-python = ">=3.12"
    dependencies    = ["openai>=1.52.2", "rich>=13.9.3"]
